### ISSUE TITLE
Tiny typo

### ISSUE THREAD

**Issue by mdagost** [thwh/hnsw#1]
Thanks for the tutorial!  Really enjoyed it and found it useful!  

I'm wondering if you have an off-by one error [here](https://github.com/brtholomy/hnsw/blob/master/hnsw.py#L32).  I think it should be `layer_i`, not `layer_i + 1`.  And also, [here](https://github.com/brtholomy/hnsw/blob/master/hnsw.py#L38), I think you can replace `min(topL, layer_i)` with just `layer_i` because of [this](https://github.com/brtholomy/hnsw/blob/master/hnsw.py#L29).

Thanks again!

**Comment by brtholomy** [comment]
Yes looks like you're right. Good close reading of the code, dude. You may like my other writing: https://www.bartholomy.ooo/posts/the-birth-of-purpose/
